### ISSUE TITLE
اطلاعات پنل

### ISSUE THREAD

**Issue by miladia13** [MrAminiNezhad/BorzooBot#1]
خط ۹۹ 
data 
چی بزاریم؟

**Comment by MrAminiNezhad** [comment]
خط 99 به این صورت تنضیم بشه 
    def run_login_script(self):
        url = 'https://site.ir:2020/login'
        data = {
            'username': 'admin',
            'password': '123'
        }

**Comment by miladia13** [comment]
https://check-host.net/check-udp?host=149.34.201.14:443&csrf_token=265360695119c20e0d26370dc4755762e24f691f

سلام ببینین پینگش بهتر شده ولی  فیلتر شده رو چند تا  پورت udp فکر نکنم بشه
استفاده کرد باید جدید بگیرم اما شانس من جدید هم بگیرم همین میشه 🙏 لطفا اگر
امکان داره دوباره چک کنین ببینین بهتر میشه اگر نه که آیپی جدید بگیرم ممنون
زحمت دادم

**Comment by miladia13** [comment]
> خط 99 به این صورت تنضیم بشه
> def run_login_script(self):
> url = 'https://site.ir:2020/login'
> data = {
> 'username': 'admin',
> 'password': '123'
> }

پس فقط آدرس پنل و یوزرنیم و پسورد اینجا وارد بشه قسمت دیتا چیزی نمیخواد درسته؟

**Comment by MrAminiNezhad** [comment]
بله فقط موارد اعلام شده را ویرایش بکنید 

البته در نسخه جدید بهینه تر شده این بخش لطفا توضیحات را بررسی بکنید
