### ISSUE TITLE
نمایش اطلاعات چندین سرور و پنل

### ISSUE THREAD

**Issue by qar4al** [MrAminiNezhad/BorzooBot#2]
سلام تشکر بابت اسکریپتی که نوشتین . ایا میشه چندین پنل رو تو یه ربات نمایش داد مشخصات کاربر ها رو ؟

**Comment by MrAminiNezhad** [comment]
سلام دوست عزیز ، 
درحال حاضر تست نشده ولی فک کنم با اجرا روی چند سرور قابل انجام باشه ... 
البته به زودی این قابلیت افزوده میشه
